In [44]:
import pandas as pd
import numpy as np

In [3]:
df=pd.Series([2,3,4])
print(df)

0    2
1    3
2    4
dtype: int64

In [7]:
#Handling null values in a csv file
#Instead of removing complete row having null values we will fill those null values 
#as by removing we may lost some important data
df=pd.read_csv(r'C:\Users\hp\Downloads\sample.csv')
df.head(10)

   Roll No.  Physics  Chemistry  Maths  Computer
0         1     56.0       57.0   58.0      59.0
1         2     23.0       24.0   25.0      26.0
2         3     89.0       25.0   26.0      27.0
3         4     45.0       26.0   27.0      28.0
4         5     23.0       27.0   28.0      29.0
5         6     90.0        NaN   29.0      30.0
6         7     12.0       13.0   14.0      15.0
7         8     78.0       14.0   15.0      16.0
8         9      NaN       15.0   16.0      17.0
9        10     45.0       16.0   17.0      18.0

In [6]:
df.isnull().sum()

Roll No.     0
Physics      3
Chemistry    4
Maths        2
Computer     1
dtype: int64

In [11]:
#Fill null or NaN values
#Filling null values with zero
df1=df.fillna(0)
df1.head(10)

   Roll No.  Physics  Chemistry  Maths  Computer
0         1     56.0       57.0   58.0      59.0
1         2     23.0       24.0   25.0      26.0
2         3     89.0       25.0   26.0      27.0
3         4     45.0       26.0   27.0      28.0
4         5     23.0       27.0   28.0      29.0
5         6     90.0        0.0   29.0      30.0
6         7     12.0       13.0   14.0      15.0
7         8     78.0       14.0   15.0      16.0
8         9      0.0       15.0   16.0      17.0
9        10     45.0       16.0   17.0      18.0

In [12]:
df1=df.fillna(2)
df1.head(10)

   Roll No.  Physics  Chemistry  Maths  Computer
0         1     56.0       57.0   58.0      59.0
1         2     23.0       24.0   25.0      26.0
2         3     89.0       25.0   26.0      27.0
3         4     45.0       26.0   27.0      28.0
4         5     23.0       27.0   28.0      29.0
5         6     90.0        2.0   29.0      30.0
6         7     12.0       13.0   14.0      15.0
7         8     78.0       14.0   15.0      16.0
8         9      2.0       15.0   16.0      17.0
9        10     45.0       16.0   17.0      18.0

In [15]:
#Here each column want to fill null values in there col with different values
#like here physics want to fill Nan value with none, Maths want to fill Nan value with 30
df1=df.fillna({"Physics":"none","Chemistry":0,"Maths":30,"Computer":"-1"})
df1

    Roll No. Physics  Chemistry  Maths Computer
0          1    56.0       57.0   58.0     59.0
1          2    23.0       24.0   25.0     26.0
2          3    89.0       25.0   26.0     27.0
3          4    45.0       26.0   27.0     28.0
4          5    23.0       27.0   28.0     29.0
5          6    90.0        0.0   29.0     30.0
6          7    12.0       13.0   14.0     15.0
7          8    78.0       14.0   15.0     16.0
8          9    none       15.0   16.0     17.0
9         10    45.0       16.0   17.0     18.0
10        11    none       17.0   18.0     19.0
11        12    88.0        0.0   19.0     20.0
12        13    22.0       23.0   24.0     25.0
13        14    90.0        0.0   30.0     42.0
14        15    none       43.0   43.0     43.0
15        16    44.0       44.0   44.0     44.0
16        17    45.0       45.0   45.0     45.0
17        18    46.0       46.0   46.0     46.0
18        19    47.0       47.0   47.0     47.0
19        20    48.0       48.0   48.0     48.0
20        21    49.0       49.0   49.0     49.0
21        22    50.0       50.0   50.0     50.0
22        23    51.0       51.0   51.0     51.0
23        24    52.0       52.0   52.0     52.0
24        25    53.0        0.0   30.0     53.0
25        26    54.0       33.0   33.0     54.0
26        27    55.0       34.0   34.0     55.0
27        28    56.0       35.0   35.0       -1
28        29    57.0       36.0   36.0     66.0
29        30    58.0       37.0   37.0     43.0

In [19]:
#Forward fill
#Forward fill - fills the null values with just the above field value in same column
df.fillna(method="ffill") #row wise fill i.e field value just in above row here default axis=0

    Roll No.  Physics  Chemistry  Maths  Computer
0          1     56.0       57.0   58.0      59.0
1          2     23.0       24.0   25.0      26.0
2          3     89.0       25.0   26.0      27.0
3          4     45.0       26.0   27.0      28.0
4          5     23.0       27.0   28.0      29.0
5          6     90.0       27.0   29.0      30.0
6          7     12.0       13.0   14.0      15.0
7          8     78.0       14.0   15.0      16.0
8          9     78.0       15.0   16.0      17.0
9         10     45.0       16.0   17.0      18.0
10        11     45.0       17.0   18.0      19.0
11        12     88.0       17.0   19.0      20.0
12        13     22.0       23.0   24.0      25.0
13        14     90.0       23.0   24.0      42.0
14        15     90.0       43.0   43.0      43.0
15        16     44.0       44.0   44.0      44.0
16        17     45.0       45.0   45.0      45.0
17        18     46.0       46.0   46.0      46.0
18        19     47.0       47.0   47.0      47.0
19        20     48.0       48.0   48.0      48.0
20        21     49.0       49.0   49.0      49.0
21        22     50.0       50.0   50.0      50.0
22        23     51.0       51.0   51.0      51.0
23        24     52.0       52.0   52.0      52.0
24        25     53.0       52.0   52.0      53.0
25        26     54.0       33.0   33.0      54.0
26        27     55.0       34.0   34.0      55.0
27        28     56.0       35.0   35.0      55.0
28        29     57.0       36.0   36.0      66.0
29        30     58.0       37.0   37.0      43.0

In [22]:
#Forward fill col wise
df.fillna(method="ffill",axis=1) #column wise fill i.e field value just previous in before column

    Roll No.  Physics  Chemistry  Maths  Computer
0        1.0     56.0       57.0   58.0      59.0
1        2.0     23.0       24.0   25.0      26.0
2        3.0     89.0       25.0   26.0      27.0
3        4.0     45.0       26.0   27.0      28.0
4        5.0     23.0       27.0   28.0      29.0
5        6.0     90.0       90.0   29.0      30.0
6        7.0     12.0       13.0   14.0      15.0
7        8.0     78.0       14.0   15.0      16.0
8        9.0      9.0       15.0   16.0      17.0
9       10.0     45.0       16.0   17.0      18.0
10      11.0     11.0       17.0   18.0      19.0
11      12.0     88.0       88.0   19.0      20.0
12      13.0     22.0       23.0   24.0      25.0
13      14.0     90.0       90.0   90.0      42.0
14      15.0     15.0       43.0   43.0      43.0
15      16.0     44.0       44.0   44.0      44.0
16      17.0     45.0       45.0   45.0      45.0
17      18.0     46.0       46.0   46.0      46.0
18      19.0     47.0       47.0   47.0      47.0
19      20.0     48.0       48.0   48.0      48.0
20      21.0     49.0       49.0   49.0      49.0
21      22.0     50.0       50.0   50.0      50.0
22      23.0     51.0       51.0   51.0      51.0
23      24.0     52.0       52.0   52.0      52.0
24      25.0     53.0       53.0   53.0      53.0
25      26.0     54.0       33.0   33.0      54.0
26      27.0     55.0       34.0   34.0      55.0
27      28.0     56.0       35.0   35.0      35.0
28      29.0     57.0       36.0   36.0      66.0
29      30.0     58.0       37.0   37.0      43.0

In [25]:
#Fill null values with some particular calculated value
#see 8, 10, 14 index which have null values
df["Physics"].fillna(value=df["Physics"].mean())

0     56.000000
1     23.000000
2     89.000000
3     45.000000
4     23.000000
5     90.000000
6     12.000000
7     78.000000
8     52.814815
9     45.000000
10    52.814815
11    88.000000
12    22.000000
13    90.000000
14    52.814815
15    44.000000
16    45.000000
17    46.000000
18    47.000000
19    48.000000
20    49.000000
21    50.000000
22    51.000000
23    52.000000
24    53.000000
25    54.000000
26    55.000000
27    56.000000
28    57.000000
29    58.000000
Name: Physics, dtype: float64

In [26]:
#Backward fill - same as forward fill just the direction of taking values is opposite 
#insted of previous , just after field value is taken
#axis=0 below value of just below row (default)
df.fillna(method="bfill")

    Roll No.  Physics  Chemistry  Maths  Computer
0          1     56.0       57.0   58.0      59.0
1          2     23.0       24.0   25.0      26.0
2          3     89.0       25.0   26.0      27.0
3          4     45.0       26.0   27.0      28.0
4          5     23.0       27.0   28.0      29.0
5          6     90.0       13.0   29.0      30.0
6          7     12.0       13.0   14.0      15.0
7          8     78.0       14.0   15.0      16.0
8          9     45.0       15.0   16.0      17.0
9         10     45.0       16.0   17.0      18.0
10        11     88.0       17.0   18.0      19.0
11        12     88.0       23.0   19.0      20.0
12        13     22.0       23.0   24.0      25.0
13        14     90.0       43.0   43.0      42.0
14        15     44.0       43.0   43.0      43.0
15        16     44.0       44.0   44.0      44.0
16        17     45.0       45.0   45.0      45.0
17        18     46.0       46.0   46.0      46.0
18        19     47.0       47.0   47.0      47.0
19        20     48.0       48.0   48.0      48.0
20        21     49.0       49.0   49.0      49.0
21        22     50.0       50.0   50.0      50.0
22        23     51.0       51.0   51.0      51.0
23        24     52.0       52.0   52.0      52.0
24        25     53.0       33.0   33.0      53.0
25        26     54.0       33.0   33.0      54.0
26        27     55.0       34.0   34.0      55.0
27        28     56.0       35.0   35.0      66.0
28        29     57.0       36.0   36.0      66.0
29        30     58.0       37.0   37.0      43.0

In [27]:
#axis=1 side after value of just after column
df.fillna(method="bfill",axis=1)

    Roll No.  Physics  Chemistry  Maths  Computer
0        1.0     56.0       57.0   58.0      59.0
1        2.0     23.0       24.0   25.0      26.0
2        3.0     89.0       25.0   26.0      27.0
3        4.0     45.0       26.0   27.0      28.0
4        5.0     23.0       27.0   28.0      29.0
5        6.0     90.0       29.0   29.0      30.0
6        7.0     12.0       13.0   14.0      15.0
7        8.0     78.0       14.0   15.0      16.0
8        9.0     15.0       15.0   16.0      17.0
9       10.0     45.0       16.0   17.0      18.0
10      11.0     17.0       17.0   18.0      19.0
11      12.0     88.0       19.0   19.0      20.0
12      13.0     22.0       23.0   24.0      25.0
13      14.0     90.0       42.0   42.0      42.0
14      15.0     43.0       43.0   43.0      43.0
15      16.0     44.0       44.0   44.0      44.0
16      17.0     45.0       45.0   45.0      45.0
17      18.0     46.0       46.0   46.0      46.0
18      19.0     47.0       47.0   47.0      47.0
19      20.0     48.0       48.0   48.0      48.0
20      21.0     49.0       49.0   49.0      49.0
21      22.0     50.0       50.0   50.0      50.0
22      23.0     51.0       51.0   51.0      51.0
23      24.0     52.0       52.0   52.0      52.0
24      25.0     53.0       53.0   53.0      53.0
25      26.0     54.0       33.0   33.0      54.0
26      27.0     55.0       34.0   34.0      55.0
27      28.0     56.0       35.0   35.0       NaN
28      29.0     57.0       36.0   36.0      66.0
29      30.0     58.0       37.0   37.0      43.0

In [34]:
df.fillna(method="bfill",inplace=True)
df

    Roll No.  Physics  Chemistry  Maths  Computer
0          1     56.0       57.0   58.0      59.0
1          2     23.0       24.0   25.0      26.0
2          3     89.0       25.0   26.0      27.0
3          4     45.0       26.0   27.0      28.0
4          5     23.0       27.0   28.0      29.0
5          6     90.0       13.0   29.0      30.0
6          7     12.0       13.0   14.0      15.0
7          8     78.0       14.0   15.0      16.0
8          9     45.0       15.0   16.0      17.0
9         10     45.0       16.0   17.0      18.0
10        11     88.0       17.0   18.0      19.0
11        12     88.0       23.0   19.0      20.0
12        13     22.0       23.0   24.0      25.0
13        14     90.0       43.0   43.0      42.0
14        15     44.0       43.0   43.0      43.0
15        16     44.0       44.0   44.0      44.0
16        17     45.0       45.0   45.0      45.0
17        18     46.0       46.0   46.0      46.0
18        19     47.0       47.0   47.0      47.0
19        20     48.0       48.0   48.0      48.0
20        21     49.0       49.0   49.0      49.0
21        22     50.0       50.0   50.0      50.0
22        23     51.0       51.0   51.0      51.0
23        24     52.0       52.0   52.0      52.0
24        25     53.0       33.0   33.0      53.0
25        26     54.0       33.0   33.0      54.0
26        27     55.0       34.0   34.0      55.0
27        28     56.0       35.0   35.0      66.0
28        29     57.0       36.0   36.0      66.0
29        30     58.0       37.0   37.0      43.0

In [36]:
#sometimes we cannot use axis inplace and method at the same time
#this is due to Nan type 
#best is to change all Nan with np.nan first And then due bfill,inplace,axis together
dx=pd.read_csv(r'C:\Users\hp\Downloads\sample.csv')
print(dx.head(15))

    Roll No.  Physics  Chemistry  Maths  Computer
0          1     56.0       57.0   58.0      59.0
1          2     23.0       24.0   25.0      26.0
2          3     89.0       25.0   26.0      27.0
3          4     45.0       26.0   27.0      28.0
4          5     23.0       27.0   28.0      29.0
5          6     90.0        NaN   29.0      30.0
6          7     12.0       13.0   14.0      15.0
7          8     78.0       14.0   15.0      16.0
8          9      NaN       15.0   16.0      17.0
9         10     45.0       16.0   17.0      18.0
10        11      NaN       17.0   18.0      19.0
11        12     88.0        NaN   19.0      20.0
12        13     22.0       23.0   24.0      25.0
13        14     90.0        NaN    NaN      42.0
14        15      NaN       43.0   43.0      43.0

In [43]:
#First changing NaN values to np.nan value
dx.fillna({"Physics":np.nan,"Chemistry":np.nan,"Maths":np.nan,"Computer":np.nan},inplace=True)
print(dx)
dx.fillna(method="bfill",inplace=True)
print("After filling and saving changes in same dataframe:\n",dx.isnull().sum())

    Roll No.  Physics  Chemistry  Maths  Computer
0          1     56.0       57.0   58.0      59.0
1          2     23.0       24.0   25.0      26.0
2          3     89.0       25.0   26.0      27.0
3          4     45.0       26.0   27.0      28.0
4          5     23.0       27.0   28.0      29.0
5          6     90.0       13.0   29.0      30.0
6          7     12.0       13.0   14.0      15.0
7          8     78.0       14.0   15.0      16.0
8          9     45.0       15.0   16.0      17.0
9         10     45.0       16.0   17.0      18.0
10        11     88.0       17.0   18.0      19.0
11        12     88.0       23.0   19.0      20.0
12        13     22.0       23.0   24.0      25.0
13        14     90.0       43.0   43.0      42.0
14        15     44.0       43.0   43.0      43.0
15        16     44.0       44.0   44.0      44.0
16        17     45.0       45.0   45.0      45.0
17        18     46.0       46.0   46.0      46.0
18        19     47.0       47.0   47.0      47.0
19        20     48.0       48.0   48.0      48.0
20        21     49.0       49.0   49.0      49.0
21        22     50.0       50.0   50.0      50.0
22        23     51.0       51.0   51.0      51.0
23        24     52.0       52.0   52.0      52.0
24        25     53.0       33.0   33.0      53.0
25        26     54.0       33.0   33.0      54.0
26        27     55.0       34.0   34.0      55.0
27        28     56.0       35.0   35.0      66.0
28        29     57.0       36.0   36.0      66.0
29        30     58.0       37.0   37.0      43.0
After filling and saving changes in same dataframe:
 Roll No.     0
Physics      0
Chemistry    0
Maths        0
Computer     0
dtype: int64

In [45]:
#Replacing any value
df=pd.read_csv(r'C:\Users\hp\Downloads\sample.csv')
df.head()

   Roll No.  Physics  Chemistry  Maths  Computer
0         1     56.0       57.0   58.0      59.0
1         2     23.0       24.0   25.0      26.0
2         3     89.0       25.0   26.0      27.0
3         4     45.0       26.0   27.0      28.0
4         5     23.0       27.0   28.0      29.0

In [49]:
#all places where 26 is there is replaced by 30
df1=df.replace(to_replace=26,value=30)
df1.head()

   Roll No.  Physics  Chemistry  Maths  Computer
0         1     56.0       57.0   58.0      59.0
1         2     23.0       24.0   25.0      30.0
2         3     89.0       25.0   30.0      27.0
3         4     45.0       30.0   27.0      28.0
4         5     23.0       27.0   28.0      29.0

In [52]:
#another way - directly write values
df1=df.replace(27,100)  #first parameter is the value to be replaced and second one is the value which replacing old one
df1.head()

   Roll No.  Physics  Chemistry  Maths  Computer
0         1     56.0       57.0   58.0      59.0
1         2     23.0       24.0   25.0      26.0
2         3     89.0       25.0   26.0     100.0
3         4     45.0       26.0  100.0      28.0
4         5     23.0      100.0   28.0      29.0

In [54]:
#replacing multiple values by the same single value
print("Printing Before replacing : (top 5 rows):\n",df.head())
df1=df.replace(to_replace=[56,26,27,28],value='A')
print("\nPrinting After replacing : (top 5 rows):\n",df1.head())

Printing Before replacing : (top 5 rows):
    Roll No.  Physics  Chemistry  Maths  Computer
0         1     56.0       57.0   58.0      59.0
1         2     23.0       24.0   25.0      26.0
2         3     89.0       25.0   26.0      27.0
3         4     45.0       26.0   27.0      28.0
4         5     23.0       27.0   28.0      29.0

Printing After replacing : (top 5 rows):
   Roll No. Physics Chemistry Maths Computer
0        1       A      57.0  58.0     59.0
1        2    23.0      24.0  25.0        A
2        3    89.0      25.0     A        A
3        4    45.0         A     A        A
4        5    23.0         A     A     29.0

In [59]:
#replacing multiple values with corresponding multiple values
df1=df.replace(to_replace=[26,27,28,16,17],value=['a','b','c','c','d'])
df1.head(15)

   Roll No.  Physics Chemistry Maths Computer
0         1     56.0      57.0  58.0     59.0
1         2     23.0      24.0  25.0        a
2         3     89.0      25.0     a        b
3         4     45.0         a     b        c
4         5     23.0         b     c     29.0
5         6     90.0       NaN  29.0     30.0
6         7     12.0      13.0  14.0     15.0
7         8     78.0      14.0  15.0        c
8         9      NaN      15.0     c        d
9        10     45.0         c     d     18.0
10       11      NaN         d  18.0     19.0
11       12     88.0       NaN  19.0     20.0
12       13     22.0      23.0  24.0     25.0
13       14     90.0       NaN   NaN     42.0
14       15      NaN      43.0  43.0     43.0

In [62]:
#changes made only to physics column and saved in original dataframe due to inplace=True
df["Physics"].replace(to_replace=[12,16,22,90,20],value=['a','b','c','c','d'],inplace=True)
df.head(15)

    Roll No. Physics  Chemistry  Maths  Computer
0          1    56.0       57.0   58.0      59.0
1          2    23.0       24.0   25.0      26.0
2          3    89.0       25.0   26.0      27.0
3          4    45.0       26.0   27.0      28.0
4          5    23.0       27.0   28.0      29.0
5          6       c        NaN   29.0      30.0
6          7       a       13.0   14.0      15.0
7          8    78.0       14.0   15.0      16.0
8          9     NaN       15.0   16.0      17.0
9         10    45.0       16.0   17.0      18.0
10        11     NaN       17.0   18.0      19.0
11        12    88.0        NaN   19.0      20.0
12        13       c       23.0   24.0      25.0
13        14       c        NaN    NaN      42.0
14        15     NaN       43.0   43.0      43.0

In [69]:
#replacing using regex
df1=df.replace('[A-Za-z]',0.0,regex=True)
df1.head(15)

    Roll No. Physics  Chemistry  Maths  Computer
0          1    56.0       57.0   58.0      59.0
1          2    23.0       24.0   25.0      26.0
2          3    89.0       25.0   26.0      27.0
3          4    45.0       26.0   27.0      28.0
4          5    23.0       27.0   28.0      29.0
5          6     0.0        NaN   29.0      30.0
6          7     0.0       13.0   14.0      15.0
7          8    78.0       14.0   15.0      16.0
8          9     NaN       15.0   16.0      17.0
9         10    45.0       16.0   17.0      18.0
10        11     NaN       17.0   18.0      19.0
11        12    88.0        NaN   19.0      20.0
12        13     0.0       23.0   24.0      25.0
13        14     0.0        NaN    NaN      42.0
14        15     NaN       43.0   43.0      43.0

In [72]:
#replacing by forward and backward fill
df1=df.replace(to_replace=[26,27,28],method="bfill")
df1.head(8)

   Roll No. Physics  Chemistry  Maths  Computer
0         1    56.0       57.0   58.0      59.0
1         2    23.0       24.0   25.0      29.0
2         3    89.0       25.0   29.0      29.0
3         4    45.0        NaN   29.0      29.0
4         5    23.0        NaN   29.0      29.0
5         6       c        NaN   29.0      30.0
6         7       a       13.0   14.0      15.0
7         8    78.0       14.0   15.0      16.0