In [ ]:
#Pandas library is used for manupulation and analysis of data

In [2]:
import pandas as pd
import numpy as np

In [2]:
pd.__version__

'1.3.4'

In [14]:
#series is a collection of data in pandas
#Creating panda series using list
list1=[1,2,3,4,5,6]
print(list1)

series=pd.Series(list1) #here each element of list1 will be element of a column 
print(series) #Series changes list to columns along with indices
print(type(series))

[1, 2, 3, 4, 5, 6]
0    1
1    2
2    3
3    4
4    5
5    6
dtype: int64
<class 'pandas.core.series.Series'>

In [6]:
#empty series
#By default data type will be float64
empty=pd.Series([])
empty

C:\Users\hp\AppData\Local\Temp/ipykernel_4220/2282263889.py:3: DeprecationWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  empty=pd.Series([])

Series([], dtype: float64)

In [9]:
#Making our own indices
a=pd.Series(['a','b','c','d','e'],index=[5,7,9,11,'x'])
print(a)

5     a
7     b
9     c
11    d
x     e
dtype: object

In [10]:
#Giving name of the series
a=pd.Series(['a','b','c','d','e'],index=[10,11,12,13,14],name='alphabets')
print(a)

10    a
11    b
12    c
13    d
14    e
Name: alphabets, dtype: object

In [13]:
#Making scaler values
s=pd.Series(0.5)
print(s)

s2=pd.Series(0.5,index=[1,2,3])
print(s2)

0    0.5
dtype: float64
1    0.5
2    0.5
3    0.5
dtype: float64

In [3]:
#Creating panda series using dictionary
dic1=pd.Series({1:'p',2:'q',3:'r','x':'t'})
print(dic1)  #keys will be index and value will be columns

dic2=pd.Series({'p':1,'q':2,'r':3})
print(dic2) #data type is the data type of column

print("Accesing particular column value:",dic2[2])
print("Accesing whole row:",dic2[2:3])
print("Accessing set of rows:",dic2[1:3])

print("Max element in dictionary:",max(dic2))

1    p
2    q
3    r
x    t
dtype: object
p    1
q    2
r    3
dtype: int64
Accesing particular column value: 3
Accesing whole row: r    3
dtype: int64
Accessing set of rows: q    2
r    3
dtype: int64
Max element in dictionary: 3

In [5]:
#List as values or as column in dictionary series
dic=pd.Series({'p':[1,2,3,4],'q':[5,6,7,8],'r':[9,10,11,12]})
print(dic)

p       [1, 2, 3, 4]
q       [5, 6, 7, 8]
r    [9, 10, 11, 12]
dtype: object

In [35]:
#Panda Dataframe
#Dataframe is a collection of data that contains rows and columns
#dataframe files can be created manually or by csv or excel files
df=pd.DataFrame()
print(df)

#Dataframe by list
list1=[1,2,3,4,1,'s']
dfl=pd.DataFrame(list1)
print("Dataframe by list:\n",dfl) #output 1 col represented by 0 index and 6 rows(0 to 5 index)
type(dfl)

Empty DataFrame
Columns: []
Index: []
Dataframe by list:
    0
0  1
1  2
2  3
3  4
4  1
5  s

pandas.core.frame.DataFrame

In [13]:
#Dataframe by multiple columns
lst=[[1,2,3,4,5],[5,6,7,8,9]]
df=pd.DataFrame(lst)
print("Multiple rows and columns Dataframe:\n",df)

#Dataframe by Multiple rows and cols with the help of numpy nD array
lst2=np.arange(0,20).reshape(5,4)
df2=pd.DataFrame(lst2)
print("Multiple rows and cols with the help of numpy nD array :\n",df2)

Multiple rows and columns Dataframe:
    0  1  2  3  4
0  1  2  3  4  5
1  5  6  7  8  9
Multiple rows and cols with the help of numpy nD array :
     0   1   2   3
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15
4  16  17  18  19

In [20]:
#Dataframe by dictionary
a=[{'a':1,'b':2,'c':3,'d':5},{'a':7,'b':8,'c':9,'d':10}]   #Dictionary keys represent column names and values will be element in each row
df=pd.DataFrame(a)
print("Dataframe with list of dictionaries:\n",df)

Dataframe with list of dictionaries:
    a  b  c   d
0  1  2  3   5
1  7  8  9  10

In [19]:
#Dataframe using dictionaries with multiple values for each key
x={
    "Roll No.":pd.Series([1,2,3,4,5]),
    "Maths":pd.Series([78,90,56,82,97]),
    "Physics":pd.Series([82,78,98,79,87])
}

df=pd.DataFrame(x)
print(df)

   Roll No.  Maths  Physics
0         1     78       82
1         2     90       78
2         3     56       98
3         4     82       79
4         5     97       87

In [26]:
#Creating a csv file and populating data in it
import csv

data = [
    [1.0, 7890.0],
    [2.0, 6000.8],
    [3.0, 8500.5],
    [8.0, 12000.0],
    [2.0, 6100.0],
    [9.0, 13500.2],
    [4.5, 9000.7],
    [5.0, 9700.0],
    [6.0, 10500.3],
    [7.5, 11200.6],
    [3.2, 8200.4],
    [1.5, 7300.1],
    [2.8, 7900.0],
    [4.0, 8800.0],
    [6.5, 10800.0],
]

#newline=''	This prevents Python from inserting extra blank lines between rows when writing CSV files on Windows. 
#It ensures newlines are handled consistently.
with open("Salary_Data.csv",'w',newline='') as file:    #if Salary_Data.csv is not there it will create it
    writer=csv.writer(file)
    writer.writerow(["YearsExperience", "Salary"])
    writer.writerows(data)

#Read file content
with open("Salary_Data.csv","r") as file:
    contents=file.read()
print("Files in Salary.csv:\n",contents)

Files in Salary.csv:
 YearsExperience,Salary
1.0,7890.0
2.0,6000.8
3.0,8500.5
8.0,12000.0
2.0,6100.0
9.0,13500.2
4.5,9000.7
5.0,9700.0
6.0,10500.3
7.5,11200.6
3.2,8200.4
1.5,7300.1
2.8,7900.0
4.0,8800.0
6.5,10800.0

In [33]:
#Reading CSV as DataFrames
#df=pd.read_csv('Salary_Data.csv') #here r is not required as it is in localhost only
df=pd.read_csv(r'C:\Users\hp\Downloads\Salary_Data.csv') #here r represent raw path wchich help to access file from local system
print(df)
type(df)

    YearsExperience   Salary
0               1.0   7890.0
1               2.0   6000.8
2               3.0   8500.5
3               8.0  12000.0
4               2.0   6100.0
5               9.0  13500.2
6               4.5   9000.7
7               5.0   9700.0
8               6.0  10500.3
9               7.5  11200.6
10              3.2   8200.4
11              1.5   7300.1
12              2.8   7900.0
13              4.0   8800.0
14              6.5  10800.0

pandas.core.frame.DataFrame

In [40]:
#DataFrame functions
#Functions to give dimension of data frame
df=pd.read_csv(r'C:\Users\hp\Downloads\Salary_Data.csv')
print("Getting column names:",df.columns)
print("Getting data dimension (totalrows,totalcols):",df.shape) #here to row with column names are excludes 
#df.shape gives total number of tuples
print("Getting total data:",df.size) #total number of cells

Getting column names: Index(['YearsExperience', 'Salary'], dtype='object')
Getting data dimension (totalrows,totalcols): (15, 2)
Getting total data: 30

In [46]:
#Important functions to access data
df=pd.read_csv(r'C:\Users\hp\Downloads\Salary_Data.csv')
print("Top 5 rows (by default):\n",df.head())
print("Top n rows :\n",df.head(2)) #df.head(n)
print("Last 5 rows (by default):\n",df.tail())
print("Last n rows:\n",df.tail(7))

Top 5 rows (by default):
    YearsExperience   Salary
0              1.0   7890.0
1              2.0   6000.8
2              3.0   8500.5
3              8.0  12000.0
4              2.0   6100.0
Top n rows :
    YearsExperience  Salary
0              1.0  7890.0
1              2.0  6000.8
Last 5 rows (by default):
     YearsExperience   Salary
10              3.2   8200.4
11              1.5   7300.1
12              2.8   7900.0
13              4.0   8800.0
14              6.5  10800.0
Last n rows:
     YearsExperience   Salary
8               6.0  10500.3
9               7.5  11200.6
10              3.2   8200.4
11              1.5   7300.1
12              2.8   7900.0
13              4.0   8800.0
14              6.5  10800.0

In [52]:
#Getting all important details by .describe()
#getting basic math functions like mean,count of rows,min, standard deviation,etc
df=pd.read_csv(r'C:\Users\hp\Downloads\Salary_Data.csv')
df.describe()

#for 25% calculation is (25/100)*(15+1)=4 which means 4th index value is 25 percentile i.e 2 here for YearExperience
#but it also used interpolation so it gives 2.4
# In the output of df.describe(), the row labeled 25% corresponds to the 25th percentile, also known as the first quartile (Q1).

# 📌 What does the 25% row mean?
# It shows the value below which 25% of the data lies. In other words:

# For YearsExperience, 25% = 2.4
# → This means 25% of the employees have 2.4 or fewer years of experience.

# For Salary, 25% = 7895.0
# → This means 25% of the salaries are less than or equal to ₹7895.

# Why is this useful?
# Percentiles help you understand the spread and distribution of your data:

# 25% (Q1): Lower quartile
# 50% (Q2): Median
# 75% (Q3): Upper quartile
# Together, they are used in boxplots and also help detect outliers or skewness in data.

       YearsExperience        Salary
count        15.000000     15.000000
mean          4.400000   9159.573333
std           2.516801   2127.359317
min           1.000000   6000.800000
25%           2.400000   7895.000000
50%           4.000000   8800.000000
75%           6.250000  10650.150000
max           9.000000  13500.200000

In [53]:
#getting info about dataframe
df=df=pd.read_csv(r'C:\Users\hp\Downloads\Salary_Data.csv')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 2 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   YearsExperience  15 non-null     float64
 1   Salary           15 non-null     float64
dtypes: float64(2)
memory usage: 368.0 bytes

In [61]:
#Handling Null values
#getting info about dataframe restaurant.csv
#Dataframe cinsists of null values
df=df=pd.read_csv(r'C:\Users\hp\Downloads\restaurant.csv')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 250 entries, 0 to 249
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Rank              250 non-null    int64
 1   Restaurant        250 non-null    object
 2   Content           33 non-null     object
 3   Sales             250 non-null    int64
 4   YOY_Sales         250 non-null    object
 5   Units             250 non-null    int64
 6   YOY_Units         250 non-null    object
 7   Headquarters      52 non-null     object
 8   Segment_Category  250 non-null    object
dtypes: int64(3), object(6)
memory usage: 17.7+ KB

In [56]:
df2=pd.read_csv(r'C:\Users\hp\Downloads\restaurant.csv')
df2.head()

,Rank,Restaurant,Content,Sales,YOY_Sales,Units,YOY_Units,Headquarters,Segment_Category
0,1,McDonald's,NaN,40412,4.9%,13846,-0.5%,NaN,Quick Service & Burger
1,2,Starbucks,NaN,21380,8.6%,15049,3.0%,NaN,Quick Service & Coffee Cafe
2,3,Chick-fil-A,While Popeyes got a lot of the chicken buzz in...,11320,13.0%,2470,5.0%,NaN,Quick Service & Chicken
3,4,Taco Bell,NaN,11293,9.0%,6766,2.7%,NaN,Quick Service & Mexican
4,5,Burger King,NaN,10204,2.7%,7346,0.2%,NaN,Quick Service & Burger

In [57]:
df2.shape

(250, 9)

In [59]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 250 entries, 0 to 249
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Rank              250 non-null    int64
 1   Restaurant        250 non-null    object
 2   Content           33 non-null     object
 3   Sales             250 non-null    int64
 4   YOY_Sales         250 non-null    object
 5   Units             250 non-null    int64
 6   YOY_Units         250 non-null    object
 7   Headquarters      52 non-null     object
 8   Segment_Category  250 non-null    object
dtypes: int64(3), object(6)
memory usage: 17.7+ KB

In [60]:
df2.describe()

             Rank        Sales         Units
count  250.000000    250.00000    250.000000
mean   125.500000   1242.74000    850.076000
std     72.312977   3365.22882   2296.151659
min      1.000000    126.00000     13.000000
25%     63.250000    181.00000     85.000000
50%    125.500000    330.00000    207.000000
75%    187.750000    724.75000    555.250000
max    250.000000  40412.00000  23801.000000

In [64]:
#Handling Null datas
df3=pd.read_csv(r'C:\Users\hp\Downloads\sample.csv')
print("Top 5 rows:\n",df3.head())
df3.isnull() #gives true for null value

Top 5 rows:
    Roll No.  Physics  Chemistry  Maths  Computer
0         1     56.0       57.0   58.0      59.0
1         2     23.0       24.0   25.0      26.0
2         3     89.0       25.0   26.0      27.0
3         4     45.0       26.0   27.0      28.0
4         5     23.0       27.0   28.0      29.0

    Roll No.  Physics  Chemistry  Maths  Computer
0      False    False      False  False     False
1      False    False      False  False     False
2      False    False      False  False     False
3      False    False      False  False     False
4      False    False      False  False     False
5      False    False       True  False     False
6      False    False      False  False     False
7      False    False      False  False     False
8      False     True      False  False     False
9      False    False      False  False     False
10     False     True      False  False     False
11     False    False       True  False     False
12     False    False      False  False     False
13     False    False       True   True     False
14     False     True      False  False     False
15     False    False      False  False     False
16     False    False      False  False     False
17     False    False      False  False     False
18     False    False      False  False     False
19     False    False      False  False     False
20     False    False      False  False     False
21     False    False      False  False     False
22     False    False      False  False     False
23     False    False      False  False     False
24     False    False       True   True     False
25     False    False      False  False     False
26     False    False      False  False     False
27     False    False      False  False      True
28     False    False      False  False     False
29     False    False      False  False     False

In [68]:
#Getting number of null values
print("Getting sum of null cells or values for each column :\n",df3.isnull().sum())
print("Total of all null values:",df3.isnull().sum().sum())

Getting sum of null cells or values for each column :
 Roll No.     0
Physics      3
Chemistry    4
Maths        2
Computer     1
dtype: int64
Total of all null values: 10

In [78]:
#Dropping rows consisting of null values or NaN values
#axis=1 for col and axis=0 for rows

#All rows consisting of atleast one null value is dropped
print("Before dropping rows with a null value (rows,cols):",df3.shape)

#Dropping rows with atleast a null value
df4=df3.dropna() #default axis = 0 (row wise) , in numpy axis=1 is for row wise sum in matrix

print("After dropping rows with a null value (rows,cols):",df4.shape)

Before dropping rows with a null value (rows,cols): (30, 5)
After dropping rows with a null value (rows,cols): (22, 5)

In [79]:
#Dropping columns consisting of null values or NaN values
#axis=1 for col and axis=0 for rows

#All columns consisting of atleast one null value is dropped
print("Before dropping rows with a null value (rows,cols):",df3.shape)

#Dropping columns with atleast a null value and storing in another dataframe
df4=df3.dropna(axis=1)  #axis=1 for column wise , in numpy axis=0 is for column wise sum in matrix

print("After dropping rows with a null value (rows,cols):",df4.shape)

Before dropping rows with a null value (rows,cols): (30, 5)
After dropping rows with a null value (rows,cols): (30, 1)

In [84]:
#Dropping rows accoring to any or all
print("Shape Before dropping rows:",df3.shape)
dfx=df3.dropna(how="any") #if any row value is null remove that row
print("After dropping rows with any null value:",dfx.shape)

dfy=df3.dropna(how="all") #if all row values is null remove that row
print("After dropping rows with all null values:",dfy.shape)

Shape Before dropping rows: (30, 5)
After dropping rows with any null value: (22, 5)
After dropping rows with all null values: (30, 5)

In [86]:
#replacing original datafram i.e changes will be done in original dataframe
#this is done by setting inplace=True
print("Shape Before dropping cols :",df3.shape)
df3.dropna(axis=1,inplace=True,how='any')
print("Shape after dropping cols :",df3.shape)

Shape Before dropping cols : (30, 5)
Shape after dropping cols : (30, 1)

In [5]:
#accessing different column in csv file
df=pd.read_csv("Salary_Data.csv")
print("Accessing Salary column data:\n",df["Salary"])

Accessing Salary column data:
 0      7890.0
1      6000.8
2      8500.5
3     12000.0
4      6100.0
5     13500.2
6      9000.7
7      9700.0
8     10500.3
9     11200.6
10     8200.4
11     7300.1
12     7900.0
13     8800.0
14    10800.0
Name: Salary, dtype: float64

In [13]:
#Filtering rows
df1=df[(df["YearsExperience"]>4) & (df["Salary"]>8000)]
print("Conditional statement with 'and' operator:\n",df1)

df2=df[(df["YearsExperience"]>7) | (df["Salary"]>10000)]
print("\nConditional statement with 'or' operator:\n",df2)

df3=df[~(df["YearsExperience"]>7)]
print("\nConditional statement with 'not' operator:\n",df3)

Conditional statement with 'and' operator:
     YearsExperience   Salary
3               8.0  12000.0
5               9.0  13500.2
6               4.5   9000.7
7               5.0   9700.0
8               6.0  10500.3
9               7.5  11200.6
14              6.5  10800.0

Conditional statement with 'or' operator:
     YearsExperience   Salary
3               8.0  12000.0
5               9.0  13500.2
8               6.0  10500.3
9               7.5  11200.6
14              6.5  10800.0

Conditional statement with 'not' operator:
     YearsExperience   Salary
0               1.0   7890.0
1               2.0   6000.8
2               3.0   8500.5
4               2.0   6100.0
6               4.5   9000.7
7               5.0   9700.0
8               6.0  10500.3
10              3.2   8200.4
11              1.5   7300.1
12              2.8   7900.0
13              4.0   8800.0
14              6.5  10800.0

In [14]:
#Getting only few rows
dfx=pd.read_csv(r'C:\Users\hp\Downloads\sample.csv')
print("Getting only Rollno,Physics and Maths column values:\n",dfx[["Roll No.","Maths","Physics"]])

Getting only Rollno,Physics and Maths column values:
     Roll No.  Maths  Physics
0          1   58.0     56.0
1          2   25.0     23.0
2          3   26.0     89.0
3          4   27.0     45.0
4          5   28.0     23.0
5          6   29.0     90.0
6          7   14.0     12.0
7          8   15.0     78.0
8          9   16.0      NaN
9         10   17.0     45.0
10        11   18.0      NaN
11        12   19.0     88.0
12        13   24.0     22.0
13        14    NaN     90.0
14        15   43.0      NaN
15        16   44.0     44.0
16        17   45.0     45.0
17        18   46.0     46.0
18        19   47.0     47.0
19        20   48.0     48.0
20        21   49.0     49.0
21        22   50.0     50.0
22        23   51.0     51.0
23        24   52.0     52.0
24        25    NaN     53.0
25        26   33.0     54.0
26        27   34.0     55.0
27        28   35.0     56.0
28        29   36.0     57.0
29        30   37.0     58.0

In [16]:
#Getting top 10 rows of these three columns
print("Getting only Rollno,Physics and Maths column values (Top 10):\n",dfx[["Roll No.","Maths","Physics"]].head(10))

Getting only Rollno,Physics and Maths column values (Top 10):
    Roll No.  Maths  Physics
0         1   58.0     56.0
1         2   25.0     23.0
2         3   26.0     89.0
3         4   27.0     45.0
4         5   28.0     23.0
5         6   29.0     90.0
6         7   14.0     12.0
7         8   15.0     78.0
8         9   16.0      NaN
9        10   17.0     45.0

In [27]:
#getting rows having null values according to particular column 
dfx[dfx["Maths"].isnull()]

    Roll No.  Physics  Chemistry  Maths  Computer
13        14     90.0        NaN    NaN      42.0
24        25     53.0        NaN    NaN      53.0

In [25]:
#printing all rows having null value in any of the column
df_res=dfx[(dfx["Physics"].isnull()) | (dfx["Chemistry"].isnull()) | (dfx["Maths"].isnull()) | (dfx["Computer"].isnull())]
print(df_res)
print("Count all such above rows:",len(df_res))

    Roll No.  Physics  Chemistry  Maths  Computer
5          6     90.0        NaN   29.0      30.0
8          9      NaN       15.0   16.0      17.0
10        11      NaN       17.0   18.0      19.0
11        12     88.0        NaN   19.0      20.0
13        14     90.0        NaN    NaN      42.0
14        15      NaN       43.0   43.0      43.0
24        25     53.0        NaN    NaN      53.0
27        28     56.0       35.0   35.0       NaN
Count all such above rows: 8

In [26]:
#printing rows having not a single null value
df_res_1=dfx[~((dfx["Physics"].isnull()) | (dfx["Chemistry"].isnull()) | (dfx["Maths"].isnull()) | (dfx["Computer"].isnull()))]
print(df_res_1)
print("Count all such above rows:",len(df_res_1))

    Roll No.  Physics  Chemistry  Maths  Computer
0          1     56.0       57.0   58.0      59.0
1          2     23.0       24.0   25.0      26.0
2          3     89.0       25.0   26.0      27.0
3          4     45.0       26.0   27.0      28.0
4          5     23.0       27.0   28.0      29.0
6          7     12.0       13.0   14.0      15.0
7          8     78.0       14.0   15.0      16.0
9         10     45.0       16.0   17.0      18.0
12        13     22.0       23.0   24.0      25.0
15        16     44.0       44.0   44.0      44.0
16        17     45.0       45.0   45.0      45.0
17        18     46.0       46.0   46.0      46.0
18        19     47.0       47.0   47.0      47.0
19        20     48.0       48.0   48.0      48.0
20        21     49.0       49.0   49.0      49.0
21        22     50.0       50.0   50.0      50.0
22        23     51.0       51.0   51.0      51.0
23        24     52.0       52.0   52.0      52.0
25        26     54.0       33.0   33.0      54.0
26        27     55.0       34.0   34.0      55.0
28        29     57.0       36.0   36.0      66.0
29        30     58.0       37.0   37.0      43.0
Count all such above rows: 22