In [2]:
import pandas as pd

In [ ]:
#loc() and iloc()
#difference is loc consider index according to given one while in iloc index always goes as 0,1,2,3,4,5......
#like here below Roll no is set as index so idex will be according to Roll No. values so it will like 1,2,3,4,... in loc
#while in iloc it will still be as 0,1,2,3,....
#in short in loc index is equal to Name of row
#loc and iloc can have different functionalities or different ways of accessing rows, columns or data
#to access one more way is df[col Name][row Name]

In [4]:
#index is here a column
df=pd.read_csv(r'C:\Users\hp\Downloads\sample2.csv',index_col=["Roll No."])
df.head()

         Section Branch  Physics  Chemistry  Maths  Computer         DOB
Roll No.
1              A     CS     56.0       57.0   58.0      59.0  01-01-2001
2              A    ECE     23.0       24.0   25.0      26.0  02-01-2001
3              B   MECH     89.0       25.0   26.0      27.0  03-01-2001
4              C   MECH     45.0       26.0   27.0      28.0  04-01-2001
5              A     CS     23.0       27.0   28.0      29.0  05-01-2001

In [28]:
#getting row with index 1 or getting 1st row
df.loc[1]

Section               A
Branch               CS
Physics            56.0
Chemistry          57.0
Maths              58.0
Computer           59.0
DOB          01-01-2001
Name: 1, dtype: object

In [29]:
#getting 5th row
df.loc[5]

Section               A
Branch               CS
Physics            23.0
Chemistry          27.0
Maths              28.0
Computer           29.0
DOB          05-01-2001
Name: 5, dtype: object

In [10]:
#getting row with index 3,4,5 and 6
df.loc[[3,4,5,6]]

         Section Branch  Physics  Chemistry  Maths  Computer         DOB
Roll No.
3              B   MECH     89.0       25.0   26.0      27.0  03-01-2001
4              C   MECH     45.0       26.0   27.0      28.0  04-01-2001
5              A     CS     23.0       27.0   28.0      29.0  05-01-2001
6              A    ECE     90.0        NaN   29.0      30.0  06-01-2001

In [11]:
#getting value from index 5 and column Physics
df.loc[5,"Physics"]

23.0

In [13]:
#getting different rows values for one column
df.loc[5:15,"Chemistry"]  #here 15 will be included

Roll No.
5     27.0
6      NaN
7     13.0
8     14.0
9     15.0
10    16.0
11    17.0
12     NaN
13    23.0
14     NaN
15    43.0
Name: Chemistry, dtype: float64

In [53]:
df.loc[3:9,["Chemistry","Maths"]]

          Chemistry  Maths
Roll No.
3              25.0   26.0
4              26.0   27.0
5              27.0   28.0
6               NaN   29.0
7              13.0   14.0
8              14.0   15.0
9              15.0   16.0

In [15]:
#printing rows satisfying some condition
df.loc[df["Physics"]>55]

         Section Branch  Physics  Chemistry  Maths  Computer         DOB
Roll No.
1              A     CS     56.0       57.0   58.0      59.0  01-01-2001
3              B   MECH     89.0       25.0   26.0      27.0  03-01-2001
6              A    ECE     90.0        NaN   29.0      30.0  06-01-2001
8              C    NaN     78.0       14.0   15.0      16.0  08-01-2001
12             C     CS     88.0        NaN   19.0      20.0  12-01-2001
14             A     CS     90.0        NaN    NaN      42.0  14-01-2001
28             C     CS     56.0       35.0   35.0       NaN  28-01-2001
29             A     CS     57.0       36.0   36.0      66.0  29-01-2001
30             A     CS     58.0       37.0   37.0      43.0  30-01-2001

In [18]:
#getting math marks where corresponding physics marks is greater than 55
print(df["Maths"][df["Physics"]>55])

Roll No.
1     58.0
3     26.0
6     29.0
8     15.0
12    19.0
14     NaN
28    35.0
29    36.0
30    37.0
Name: Maths, dtype: float64

In [25]:
#loc method for getting math marks where corresponding physics marks is greater than 80
df.loc[df["Physics"]>80,["Maths"]]   #df.loc[condition,colname]

          Maths
Roll No.
3          26.0
6          29.0
12         19.0
14          NaN

In [44]:
#iloc
#Accessing 1st row by iloc
#here 0th column is the 1st column which is Section
#Columns - 0-section, 1-branch, 2-physics, 3-chemistry, 4-maths, 5-computer, 6-DOB
#rows -0,1,2,3,4...
#here while doing slicing like df.iloc[0:4,1:6], 4 and 6 will excluded unlike loc
df.iloc[0]

Section               A
Branch               CS
Physics            56.0
Chemistry          57.0
Maths              58.0
Computer           59.0
DOB          01-01-2001
Name: 1, dtype: object

In [30]:
#passing array of indices to get one or more columns
df.iloc[[0]]

         Section Branch  Physics  Chemistry  Maths  Computer         DOB
Roll No.
1              A     CS     56.0       57.0   58.0      59.0  01-01-2001

In [31]:
df.iloc[[2,3,4]]

         Section Branch  Physics  Chemistry  Maths  Computer         DOB
Roll No.
3              B   MECH     89.0       25.0   26.0      27.0  03-01-2001
4              C   MECH     45.0       26.0   27.0      28.0  04-01-2001
5              A     CS     23.0       27.0   28.0      29.0  05-01-2001

In [39]:
#Getting all rows from 1st column i.e Section
df.iloc[:,0]

Roll No.
1     A
2     A
3     B
4     C
5     A
6     A
7     B
8     C
9     A
10    A
11    B
12    C
13    A
14    A
15    B
16    C
17    A
18    A
19    B
20    C
21    A
22    A
23    B
24    C
25    A
26    A
27    B
28    C
29    A
30    A
Name: Section, dtype: object

In [40]:
#Getting all rows from 2nd column i.e Branch
df.iloc[:,1]

Roll No.
1       CS
2      ECE
3     MECH
4     MECH
5       CS
6      ECE
7       CS
8      NaN
9      ECE
10      CS
11     ECE
12      CS
13      CS
14      CS
15     ECE
16     NaN
17    MECH
18    MECH
19     ECE
20    MECH
21    MECH
22    MECH
23     ECE
24    MECH
25    MECH
26     ECE
27      CS
28      CS
29      CS
30      CS
Name: Branch, dtype: object

In [41]:
#getting 1st to 5th row and 2nd column i.e Branch
df.iloc[0:5,1]  #or df.iloc[:5,1]
#here 0,1,2,3,4 index rows are included

Roll No.
1      CS
2     ECE
3    MECH
4    MECH
5      CS
Name: Branch, dtype: object

In [43]:
df.iloc[0:5,1:4]
#here 5th index and 4th-col is excluded

         Branch  Physics  Chemistry
Roll No.
1            CS     56.0       57.0
2           ECE     23.0       24.0
3          MECH     89.0       25.0
4          MECH     45.0       26.0
5            CS     23.0       27.0

In [3]:
#GroupBy function
df1=pd.read_csv(r'C:\Users\hp\Downloads\sample2.csv')
df1.head()

   Roll No. Section Branch  Physics  Chemistry  Maths  Computer         DOB
0         1       A     CS     56.0       57.0   58.0      59.0  01-01-2001
1         2       A    ECE     23.0       24.0   25.0      26.0  02-01-2001
2         3       B   MECH     89.0       25.0   26.0      27.0  03-01-2001
3         4       C   MECH     45.0       26.0   27.0      28.0  04-01-2001
4         5       A     CS     23.0       27.0   28.0      29.0  05-01-2001

In [8]:
branch_group=df1.groupby(by="Branch")
branch_group

In [10]:
#forms dictionary with Branch as keys and list of corresponding indices as values
branch_group.groups

{'CS': [0, 4, 6, 9, 11, 12, 13, 26, 27, 28, 29], 'ECE': [1, 5, 8, 10, 14, 18, 22, 25], 'MECH': [2, 3, 16, 17, 19, 20, 21, 23, 24]}

In [19]:
#grouping by multiple columns
branch_group=df1.groupby(by=["Branch","Section"])
print(branch_group.groups)
print("Getting list of indices for CS branch and Section A:",branch_group.groups[('CS', 'A')])
print("Checking 29 index is in CS branch and Section A:",(29 in branch_group.groups[('CS', 'A')]))
print("Checking 26 index is in ECE branch and Section A:",(26 in branch_group.groups[('ECE', 'A')]))

{('CS', 'A'): [0, 4, 9, 12, 13, 28, 29], ('CS', 'B'): [6, 26], ('CS', 'C'): [11, 27], ('ECE', 'A'): [1, 5, 8, 25], ('ECE', 'B'): [10, 14, 18, 22], ('MECH', 'A'): [16, 17, 20, 21, 24], ('MECH', 'B'): [2], ('MECH', 'C'): [3, 19, 23], (nan, 'C'): [7, 15]}
Getting list of indices for CS branch and Section A: Int64Index([0, 4, 9, 12, 13, 28, 29], dtype='int64')
Checking 29 index is in CS branch and Section A: True
Checking 26 index is in ECE branch and Section A: False

In [11]:
branch_group=df1.groupby(by=["Section","Branch"])
#print("Groups in branch_group:\n")
for groups,dataframe in branch_group:
    print(groups)
    #print(dataframe)

('A', 'CS')
('A', 'ECE')
('A', 'MECH')
('B', 'CS')
('B', 'ECE')
('B', 'MECH')
('C', 'CS')
('C', 'MECH')

In [12]:
for groups,dataframe in branch_group:
    print(groups)
    print(dataframe)

('A', 'CS')
    Roll No. Section Branch  Physics  Chemistry  Maths  Computer         DOB
0          1       A     CS     56.0       57.0   58.0      59.0  01-01-2001
4          5       A     CS     23.0       27.0   28.0      29.0  05-01-2001
9         10       A     CS     45.0       16.0   17.0      18.0  10-01-2001
12        13       A     CS     22.0       23.0   24.0      25.0  13-01-2001
13        14       A     CS     90.0        NaN    NaN      42.0  14-01-2001
28        29       A     CS     57.0       36.0   36.0      66.0  29-01-2001
29        30       A     CS     58.0       37.0   37.0      43.0  30-01-2001
('A', 'ECE')
    Roll No. Section Branch  Physics  Chemistry  Maths  Computer         DOB
1          2       A    ECE     23.0       24.0   25.0      26.0  02-01-2001
5          6       A    ECE     90.0        NaN   29.0      30.0  06-01-2001
8          9       A    ECE      NaN       15.0   16.0      17.0  09-01-2001
25        26       A    ECE     54.0       33.0   33.0      54.0  26-01-2001
('A', 'MECH')
    Roll No. Section Branch  Physics  Chemistry  Maths  Computer         DOB
16        17       A   MECH     45.0       45.0   45.0      45.0  17-01-2001
17        18       A   MECH     46.0       46.0   46.0      46.0  18-01-2001
20        21       A   MECH     49.0       49.0   49.0      49.0  21-01-2001
21        22       A   MECH     50.0       50.0   50.0      50.0  22-01-2001
24        25       A   MECH     53.0        NaN    NaN      53.0  25-01-2001
('B', 'CS')
    Roll No. Section Branch  Physics  Chemistry  Maths  Computer         DOB
6          7       B     CS     12.0       13.0   14.0      15.0  07-01-2001
26        27       B     CS     55.0       34.0   34.0      55.0  27-01-2001
('B', 'ECE')
    Roll No. Section Branch  Physics  Chemistry  Maths  Computer         DOB
10        11       B    ECE      NaN       17.0   18.0      19.0  11-01-2001
14        15       B    ECE      NaN       43.0   43.0      43.0  15-01-2001
18        19       B    ECE     47.0       47.0   47.0      47.0  19-01-2001
22        23       B    ECE     51.0       51.0   51.0      51.0  23-01-2001
('B', 'MECH')
   Roll No. Section Branch  Physics  Chemistry  Maths  Computer         DOB
2         3       B   MECH     89.0       25.0   26.0      27.0  03-01-2001
('C', 'CS')
    Roll No. Section Branch  Physics  Chemistry  Maths  Computer         DOB
11        12       C     CS     88.0        NaN   19.0      20.0  12-01-2001
27        28       C     CS     56.0       35.0   35.0       NaN  28-01-2001
('C', 'MECH')
    Roll No. Section Branch  Physics  Chemistry  Maths  Computer         DOB
3          4       C   MECH     45.0       26.0   27.0      28.0  04-01-2001
19        20       C   MECH     48.0       48.0   48.0      48.0  20-01-2001
23        24       C   MECH     52.0       52.0   52.0      52.0  24-01-2001

In [17]:
#Merge Function - merge two dataframes according to an intersecting or common column
dfx=pd.DataFrame({"Roll No.":[1,2,3,4,5],"Maths":[34,56,88,21,97]})
dfx

   Roll No.  Maths
0         1     34
1         2     56
2         3     88
3         4     21
4         5     97

In [18]:
dfy=pd.DataFrame({"Roll No.":[1,2,3,4,5],"Physics":[29,47,88,72,67]})
dfy

   Roll No.  Physics
0         1       29
1         2       47
2         3       88
3         4       72
4         5       67

In [19]:
pd.merge(dfx,dfy,on="Roll No.")

   Roll No.  Maths  Physics
0         1     34       29
1         2     56       47
2         3     88       88
3         4     21       72
4         5     97       67

In [20]:
pd.merge(dfy,dfx,on="Roll No.")

   Roll No.  Physics  Maths
0         1       29     34
1         2       47     56
2         3       88     88
3         4       72     21
4         5       67     97

In [21]:
pd.merge(dfx,dfy) #on default intersecting column which is Roll No. is taken

   Roll No.  Maths  Physics
0         1     34       29
1         2     56       47
2         3     88       88
3         4     21       72
4         5     97       67

In [23]:
#When the intersecting column has different values
#here only the  values of intersecting col that is in both DataFrame will produce the output
df1=pd.DataFrame({"Roll No.":[1,2,3,4,5],"Maths":[34,56,88,21,97]})
df2=pd.DataFrame({"Roll No.":[1,2,7,4,9],"Physics":[29,47,88,72,67]})
pd.merge(df1,df2) #here Roll no 1,2 & 4 is present in both so they will be there in output after merging

   Roll No.  Maths  Physics
0         1     34       29
1         2     56       47
2         4     21       72

In [24]:
#to get remaining unmatched rollno. in above case
#according to any one dataframe
pd.merge(df1,df2,how="left")

   Roll No.  Maths  Physics
0         1     34     29.0
1         2     56     47.0
2         3     88      NaN
3         4     21     72.0
4         5     97      NaN

In [25]:
pd.merge(df1,df2,how="right")

   Roll No.  Maths  Physics
0         1   34.0       29
1         2   56.0       47
2         7    NaN       88
3         4   21.0       72
4         9    NaN       67

In [26]:
#outer will take all the rollno.
pd.merge(df1,df2,how="outer")

   Roll No.  Maths  Physics
0         1   34.0     29.0
1         2   56.0     47.0
2         3   88.0      NaN
3         4   21.0     72.0
4         5   97.0      NaN
5         7    NaN     88.0
6         9    NaN     67.0

In [27]:
#append() function - appends one dataframe to another
df1=pd.DataFrame({"Roll No.":[1,2,3,4,5],"Maths":[34,56,88,21,97],"Physics":[29,47,88,72,67]})
df2=pd.DataFrame({"Roll No.":[6,7,8,9,10],"Maths":[84,59,61,85,91],"Physics":[82,57,81,44,60]})
print(df1)
print(df2)

   Roll No.  Maths  Physics
0         1     34       29
1         2     56       47
2         3     88       88
3         4     21       72
4         5     97       67
   Roll No.  Maths  Physics
0         6     84       82
1         7     59       57
2         8     61       81
3         9     85       44
4        10     91       60

In [28]:
df1.append(df2)

   Roll No.  Maths  Physics
0         1     34       29
1         2     56       47
2         3     88       88
3         4     21       72
4         5     97       67
0         6     84       82
1         7     59       57
2         8     61       81
3         9     85       44
4        10     91       60

In [29]:
df2.append(df1)

   Roll No.  Maths  Physics
0         6     84       82
1         7     59       57
2         8     61       81
3         9     85       44
4        10     91       60
0         1     34       29
1         2     56       47
2         3     88       88
3         4     21       72
4         5     97       67

In [30]:
#ignore_index will maintain continuity of indices
df1.append(df2,ignore_index=True)

   Roll No.  Maths  Physics
0         1     34       29
1         2     56       47
2         3     88       88
3         4     21       72
4         5     97       67
5         6     84       82
6         7     59       57
7         8     61       81
8         9     85       44
9        10     91       60

In [31]:
#sort will sort according to column name
df1.append(df2,ignore_index=True,sort=True)

   Maths  Physics  Roll No.
0     34       29         1
1     56       47         2
2     88       88         3
3     21       72         4
4     97       67         5
5     84       82         6
6     59       57         7
7     61       81         8
8     85       44         9
9     91       60        10

In [33]:
#in case any column is not present in any dataframe but present in other then NaN will be displayed for that dataframe
df3=pd.DataFrame({"Roll No.":[6,7,8,9,10],"Maths":[84,59,61,85,91],"Physics":[82,57,81,44,60],"Chemistry":[45,39,80,49,90]})
df1.append(df3,ignore_index=True)

   Roll No.  Maths  Physics  Chemistry
0         1     34       29        NaN
1         2     56       47        NaN
2         3     88       88        NaN
3         4     21       72        NaN
4         5     97       67        NaN
5         6     84       82       45.0
6         7     59       57       39.0
7         8     61       81       80.0
8         9     85       44       49.0
9        10     91       60       90.0

In [39]:
#Pivot table
dfp=pd.read_csv(r'C:\Users\hp\Downloads\sample2.csv')
dfp.head()

   Roll No. Section Branch  Physics  Chemistry  Maths  Computer         DOB
0         1       A     CS     56.0       57.0   58.0      59.0  01-01-2001
1         2       A    ECE     23.0       24.0   25.0      26.0  02-01-2001
2         3       B   MECH     89.0       25.0   26.0      27.0  03-01-2001
3         4       C   MECH     45.0       26.0   27.0      28.0  04-01-2001
4         5       A     CS     23.0       27.0   28.0      29.0  05-01-2001

In [36]:
#here data will be mean of all marks belonging to the particular Branch and Subject
#like (CS,Chemistry) - 30.888889 here it means mean of all marks belonging to Cs branch and chemistry subject
#like (CS,Roll No.) - 16 here it means mean of all roll nos. belonging to cs branch
#so we can find out by seeing average marks of cs students in chemistry subject, in Maths subject,etc respectively
#while calculating if 11 rows are there out of which 2 are null or NaN then calculation will be (marks in those 9 cols/9)
pd.pivot_table(dfp,index="Branch")

        Chemistry   Computer   Maths    Physics   Roll No.
Branch
CS      30.888889  37.200000  30.200  51.090909  16.000000
ECE     32.857143  35.875000  32.750  53.000000  13.875000
MECH    42.625000  44.222222  42.875  53.000000  17.111111

In [38]:
#by default pivot calculates mean or average according to index
#we can also calculate other parameters by using aggfunc
#like here we are calculating sum according to index instead of mean
pd.pivot_table(dfp,index="Branch",aggfunc="sum")

        Chemistry  Computer  Maths  Physics  Roll No.
Branch
CS          278.0     372.0  302.0    562.0       176
ECE         230.0     287.0  262.0    265.0       111
MECH        341.0     398.0  343.0    477.0       154

In [41]:
x=dfp["Chemistry"][dfp["Branch"]=="CS"]
print(x)
print(len(x))

0     57.0
4     27.0
6     13.0
9     16.0
11     NaN
12    23.0
13     NaN
26    34.0
27    35.0
28    36.0
29    37.0
Name: Chemistry, dtype: float64
11

In [43]:
pd.pivot_table(dfp,index="Branch",aggfunc="count")   #here NaN will be excluded

        Chemistry  Computer  DOB  Maths  Physics  Roll No.  Section
Branch
CS              9        10   11     10       11        11       11
ECE             7         8    8      8        5         8        8
MECH            8         9    9      8        9         9        9

In [44]:
pd.pivot_table(dfp,index="Branch",aggfunc="max")

        Chemistry  Computer         DOB  Maths  Physics  Roll No. Section
Branch
CS           57.0      66.0  30-01-2001   58.0     90.0        30       C
ECE          51.0      54.0  26-01-2001   51.0     90.0        26       B
MECH         52.0      53.0  25-01-2001   52.0     89.0        25       C

In [48]:
#calculation is shown according to data belonging to given branch in given section like mix marks in (CS,A)
pd.pivot_table(dfp,index="Branch",columns="Section",aggfunc="min")

        Chemistry             Computer                     DOB              \
Section         A     B     C        A     B     C           A           B
Branch
CS           16.0  13.0  35.0     18.0  15.0  20.0  01-01-2001  07-01-2001
ECE          15.0  17.0   NaN     17.0  19.0   NaN  02-01-2001  11-01-2001
MECH         45.0  25.0  26.0     45.0  27.0  28.0  17-01-2001  03-01-2001

                    Maths             Physics             Roll No.
Section           C     A     B     C       A     B     C        A     B     C
Branch
CS       12-01-2001  17.0  14.0  19.0    22.0  12.0  56.0      1.0   7.0  12.0
ECE             NaN  16.0  18.0   NaN    23.0  47.0   NaN      2.0  11.0   NaN
MECH     04-01-2001  45.0  26.0  27.0    45.0  89.0  45.0     17.0   3.0   4.0

In [49]:
pd.pivot_table(dfp,index="Branch",columns="Section")

         Chemistry               Computer                       Maths         \
Section          A     B     C          A     B          C          A      B
Branch
CS       32.666667  23.5  35.0  40.285714  35.0  20.000000  33.333333  24.00
ECE      24.000000  39.5   NaN  31.750000  40.0        NaN  25.750000  39.75
MECH     47.500000  25.0  42.0  48.600000  27.0  42.666667  47.500000  26.00

                      Physics                    Roll No.
Section          C          A     B          C          A     B     C
Branch
CS       27.000000  50.142857  33.5  72.000000  14.571429  17.0  20.0
ECE            NaN  55.666667  49.0        NaN  10.750000  17.0   NaN
MECH     42.333333  48.600000  89.0  48.333333  20.600000   3.0  16.0

In [56]:
#writing dataframe and making csv from that data
dic={
    "Rollno":pd.Series([1,2,3,4,5,6]),
    "Physics":pd.Series([23,45,67,80,78,80]),
    "Chemistry":pd.Series([56,60,80,79,99,90])
}

df=pd.DataFrame(dic)
df

   Rollno  Physics  Chemistry
0       1       23         56
1       2       45         60
2       3       67         80
3       4       80         79
4       5       78         99
5       6       80         90

In [57]:
#copying this data from dataframe to csv file
df.to_csv("student.csv")

In [58]:
#without index
df.to_csv("student_index_false.csv",index=False)

In [3]:
harry=pd.read_csv("student_index_false.csv")
harry

   Rollno  Physics  Chemistry
0       1       23         56
1       2       45         60
2       3       67         80
3       4       80         79
4       5       78         99
5       6       80         90

In [60]:
harry["Physics"][1]

45

In [61]:
harry.index

RangeIndex(start=0, stop=6, step=1)

In [63]:
harry.index=["first","second","third","fourth","fifth","sixth"]
harry

        Rollno  Physics  Chemistry
first        1       23         56
second       2       45         60
third        3       67         80
fourth       4       80         79
fifth        5       78         99
sixth        6       80         90

In [4]:
import numpy as np
harry=pd.DataFrame(np.random.rand(20,5),index=np.arange(1,21))
harry

           0         1         2         3         4
1   0.453853  0.549614  0.227318  0.892512  0.204477
2   0.461709  0.170024  0.534222  0.430821  0.989934
3   0.593604  0.484441  0.348610  0.656489  0.508435
4   0.004148  0.754704  0.331341  0.229472  0.322263
5   0.497348  0.747918  0.219490  0.891600  0.956859
6   0.309397  0.446211  0.997016  0.637662  0.192854
7   0.770613  0.324580  0.804878  0.863400  0.425556
8   0.261897  0.427092  0.006389  0.820861  0.079052
9   0.592129  0.740424  0.648449  0.275135  0.767214
10  0.959807  0.159361  0.451525  0.729897  0.741208
11  0.756021  0.403672  0.107561  0.190566  0.359344
12  0.366315  0.307871  0.229487  0.135709  0.458862
13  0.024679  0.412520  0.887647  0.298799  0.573992
14  0.688734  0.754528  0.344926  0.921582  0.972900
15  0.943098  0.749073  0.506592  0.621278  0.037009
16  0.821134  0.036292  0.261302  0.597741  0.825486
17  0.032425  0.619522  0.293179  0.574960  0.490830
18  0.722184  0.366991  0.746973  0.843658  0.955975
19  0.917890  0.720210  0.796498  0.938361  0.181599
20  0.621277  0.801845  0.913253  0.635010  0.295669

In [68]:
harry.iloc[0:1,0:1]

          0
1  0.675016

In [6]:
harry.dtypes   #getting data type of all columns

0    float64
1    float64
2    float64
3    float64
4    float64
dtype: object

In [11]:
h1=harry.replace(to_replace=harry.loc[1][0],value="harry")
h1.head()

          0         1         2         3         4
1     harry  0.549614  0.227318  0.892512  0.204477
2  0.461709  0.170024  0.534222  0.430821  0.989934
3  0.593604  0.484441  0.348610  0.656489  0.508435
4  0.004148  0.754704  0.331341  0.229472  0.322263
5  0.497348  0.747918  0.219490  0.891600  0.956859

In [12]:
h1.index

Int64Index([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19,
            20],
           dtype='int64')

In [13]:
h1.columns

RangeIndex(start=0, stop=5, step=1)

In [14]:
#converting dataframe to numpy array
h1.to_numpy()

array([['harry', 0.5496138613727237, 0.22731829874743892,
        0.8925123859210771, 0.20447673092088126],
       [0.4617090995733317, 0.1700237466261224, 0.5342215354101509,
        0.4308209170273154, 0.9899342218787356],
       [0.5936041572030503, 0.4844411659599275, 0.3486103033837217,
        0.6564885709439314, 0.5084353898112649],
       [0.004147686920876081, 0.7547035624571306, 0.3313411462595728,
        0.22947237516512764, 0.32226338975763424],
       [0.49734795004582877, 0.7479179443434273, 0.21949029077714,
        0.8915999380629749, 0.9568589432311672],
       [0.30939693509969735, 0.4462107338615544, 0.9970157244881672,
        0.6376623212461003, 0.1928544765701058],
       [0.7706134377437229, 0.32458002533968666, 0.8048781642637767,
        0.8633995352836159, 0.425556237285291],
       [0.2618965980827789, 0.4270918119015661, 0.006389346728526313,
        0.8208607713575025, 0.07905221335462331],
       [0.5921292701719297, 0.7404236583949593, 0.6484494307538685,
        0.27513526509993314, 0.7672139349841912],
       [0.9598071105208528, 0.15936055494673784, 0.4515246146970331,
        0.7298973842649582, 0.7412076347259758],
       [0.7560210860258668, 0.4036721137815694, 0.10756111937342916,
        0.19056641351453651, 0.35934415709861833],
       [0.366315455680414, 0.3078709541230308, 0.22948723633050527,
        0.13570894355656882, 0.45886192898357314],
       [0.024678999731660656, 0.4125199213020887, 0.8876468765268525,
        0.29879884019238756, 0.5739918811373469],
       [0.6887337178149083, 0.7545277809063897, 0.344925743066965,
        0.9215822668492802, 0.9728998293164238],
       [0.9430976305770862, 0.7490728626139959, 0.5065922197729998,
        0.6212775289527336, 0.03700945027413427],
       [0.8211339201917053, 0.03629183992807372, 0.26130237079273944,
        0.5977410205485594, 0.8254861780735355],
       [0.03242466043513981, 0.6195220436431063, 0.2931793269284013,
        0.5749596827943038, 0.4908295612990866],
       [0.7221842517026079, 0.3669913817339644, 0.7469733995387721,
        0.8436581726511138, 0.9559750457700524],
       [0.9178903569469933, 0.7202096704150296, 0.7964976306976046,
        0.9383610535936833, 0.1815986296294182],
       [0.6212769299823343, 0.8018447753002945, 0.9132530006704872,
        0.6350096024900462, 0.29566855402463355]], dtype=object)

In [21]:
h1.replace(to_replace=h1[0][1],value=0.3,inplace=True)  #to access write df[col][row]

In [23]:
h1.head()

          0         1         2         3         4
1  0.300000  0.549614  0.227318  0.892512  0.204477
2  0.461709  0.170024  0.534222  0.430821  0.989934
3  0.593604  0.484441  0.348610  0.656489  0.508435
4  0.004148  0.754704  0.331341  0.229472  0.322263
5  0.497348  0.747918  0.219490  0.891600  0.956859

In [25]:
#Transpose a DataFrame
h1.T

,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20
0,0.300000,0.461709,0.593604,0.004148,0.497348,0.309397,0.770613,0.261897,0.592129,0.959807,0.756021,0.366315,0.024679,0.688734,0.943098,0.821134,0.032425,0.722184,0.917890,0.621277
1,0.549614,0.170024,0.484441,0.754704,0.747918,0.446211,0.324580,0.427092,0.740424,0.159361,0.403672,0.307871,0.412520,0.754528,0.749073,0.036292,0.619522,0.366991,0.720210,0.801845
2,0.227318,0.534222,0.348610,0.331341,0.219490,0.997016,0.804878,0.006389,0.648449,0.451525,0.107561,0.229487,0.887647,0.344926,0.506592,0.261302,0.293179,0.746973,0.796498,0.913253
3,0.892512,0.430821,0.656489,0.229472,0.891600,0.637662,0.863400,0.820861,0.275135,0.729897,0.190566,0.135709,0.298799,0.921582,0.621278,0.597741,0.574960,0.843658,0.938361,0.635010
4,0.204477,0.989934,0.508435,0.322263,0.956859,0.192854,0.425556,0.079052,0.767214,0.741208,0.359344,0.458862,0.573992,0.972900,0.037009,0.825486,0.490830,0.955975,0.181599,0.295669

In [26]:
h1.head()

          0         1         2         3         4
1  0.300000  0.549614  0.227318  0.892512  0.204477
2  0.461709  0.170024  0.534222  0.430821  0.989934
3  0.593604  0.484441  0.348610  0.656489  0.508435
4  0.004148  0.754704  0.331341  0.229472  0.322263
5  0.497348  0.747918  0.219490  0.891600  0.956859

In [28]:
#sorting according to index names 
#axis=0, row wise sort
#axis=1, col wise sort
#by default ascending=True
h1.sort_index(axis=0,ascending=False).head()  #row wise descending 20,19,18,...

           0         1         2         3         4
20  0.621277  0.801845  0.913253  0.635010  0.295669
19  0.917890  0.720210  0.796498  0.938361  0.181599
18  0.722184  0.366991  0.746973  0.843658  0.955975
17  0.032425  0.619522  0.293179  0.574960  0.490830
16  0.821134  0.036292  0.261302  0.597741  0.825486

In [29]:
h1.sort_index(axis=1,ascending=False).head() #col wise descending 4,3,2,...

          4         3         2         1         0
1  0.204477  0.892512  0.227318  0.549614  0.300000
2  0.989934  0.430821  0.534222  0.170024  0.461709
3  0.508435  0.656489  0.348610  0.484441  0.593604
4  0.322263  0.229472  0.331341  0.754704  0.004148
5  0.956859  0.891600  0.219490  0.747918  0.497348

In [31]:
type(h1[0])  #each column indivisually is a series in a dataframe

pandas.core.series.Series

In [33]:
#dropping any one or more columns
h1.drop([0,1],axis=1).head()

          2         3         4
1  0.227318  0.892512  0.204477
2  0.534222  0.430821  0.989934
3  0.348610  0.656489  0.508435
4  0.331341  0.229472  0.322263
5  0.219490  0.891600  0.956859

In [41]:
h1.drop(4,axis=1,inplace=True).head()  #4 col name is dropped and changed the original dataframe

KeyError: '[4] not found in axis'

In [42]:
h1.head()

          0         1         2         3
1  0.300000  0.549614  0.227318  0.892512
2  0.461709  0.170024  0.534222  0.430821
3  0.593604  0.484441  0.348610  0.656489
4  0.004148  0.754704  0.331341  0.229472
5  0.497348  0.747918  0.219490  0.891600

In [46]:
h1=h1.drop(3,axis=0).head()  #3 row name is dropped and stored in h1 only
h1

KeyError: '[3] not found in axis'

In [47]:
h1.reset_index().head()  #index is made as a new column starting from 0,1,2,....

   index         0         1         2         3
0      1  0.300000  0.549614  0.227318  0.892512
1      2  0.461709  0.170024  0.534222  0.430821
2      4  0.004148  0.754704  0.331341  0.229472
3      5  0.497348  0.747918  0.219490  0.891600
4      6  0.309397  0.446211  0.997016  0.637662

In [50]:
#to drop this column index 
h1.reset_index(drop=True,inplace=True)

In [51]:
h1.head()

          0         1         2         3
0  0.300000  0.549614  0.227318  0.892512
1  0.461709  0.170024  0.534222  0.430821
2  0.004148  0.754704  0.331341  0.229472
3  0.497348  0.747918  0.219490  0.891600
4  0.309397  0.446211  0.997016  0.637662

In [57]:
#dropping duplicate values
df=pd.DataFrame({
    "Rollno":pd.Series(np.arange(1,6)),
    "Name":pd.Series(["Rahul","Priyanka","Bablu","Rahul","Shyam"]),
    "Age":pd.Series(np.random.randint(10,20,5))
})
df

   Rollno      Name  Age
0       1     Rahul   19
1       2  Priyanka   18
2       3     Bablu   15
3       4     Rahul   12
4       5     Shyam   16

In [60]:
df.drop_duplicates(subset=["Name"])   #by default first pone is kept rest cols are dropped

   Rollno      Name  Age
0       1     Rahul   19
1       2  Priyanka   18
2       3     Bablu   15
4       5     Shyam   16

In [62]:
#using keep which decides whi occurences will remain intact after dropping duplicates
df.drop_duplicates(subset=["Name"],keep="first")  #first Rahul in index 1 is kept

   Rollno      Name  Age
0       1     Rahul   19
1       2  Priyanka   18
2       3     Bablu   15
4       5     Shyam   16

In [63]:
df.drop_duplicates(subset=["Name"],keep="last")  #Last Rahul in index 4 is kept rest are dropped here i.e at index 1 is dropped

   Rollno      Name  Age
1       2  Priyanka   18
2       3     Bablu   15
3       4     Rahul   12
4       5     Shyam   16

In [65]:
df.drop_duplicates(subset=["Name"],keep=False) #all rows with duplicate values in the specified column are dropped

   Rollno      Name  Age
1       2  Priyanka   18
2       3     Bablu   15
4       5     Shyam   16

In [66]:
df["Name"].value_counts(dropna=True)  #giving counts of each unique data in 'Name' column excluding NaN values

Rahul       2
Priyanka    1
Bablu       1
Shyam       1
Name: Name, dtype: int64

In [67]:
df.notnull().sum()  #opposite to isnull()

Rollno    5
Name      5
Age       5
dtype: int64

In [69]:
#creating a dataframe with 3 rows and 2 cols
df1=pd.DataFrame(np.arange(5,11).reshape(3,2))
df1

   0   1
0  5   6
1  7   8
2  9  10

In [73]:
print("Count of data in each col:\n",df1.count())
print("\nMax:\n",df.max())
print("\nMin:\n",df.min())
print("\nMean:\n",df.mean())
print("\nStandard deviation:\n",df.std())
print("\nMedian:\n",df.median())

Count of data in each col:
 0    3
1    3
dtype: int64

Max:
 Rollno        5
Name      Shyam
Age          19
dtype: object

Min:
 Rollno        1
Name      Bablu
Age          12
dtype: object

Mean:
 Rollno     3.0
Age       16.0
dtype: float64

Standard deviation:
 Rollno    1.581139
Age       2.738613
dtype: float64

Median:
 Rollno     3.0
Age       16.0
dtype: float64

C:\Users\hp\AppData\Local\Temp/ipykernel_9728/2884526942.py:4: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  print("\nMean:\n",df.mean())
C:\Users\hp\AppData\Local\Temp/ipykernel_9728/2884526942.py:5: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  print("\nStandard deviation:\n",df.std())
C:\Users\hp\AppData\Local\Temp/ipykernel_9728/2884526942.py:6: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  print("\nMedian:\n",df.median())

In [76]:
#here excel file consists of two sheets
dfe=pd.read_excel(r'C:\Users\hp\Downloads\employee.xlsx')  #by default sheet 1 is read
dfe

       Name  Age    Place
0     Suraj   34   Jaipur
1     Aditi   44  Kolkata
2  Priyanka   50     Pune

In [81]:
#there are two sheets in excel file
#reading the two sheets in employee.xlsx
dfe1=pd.read_excel(r'C:\Users\hp\Downloads\employee.xlsx',sheet_name="Detail1")
print("Sheet 1 details:\n")
dfe1

Sheet 1 details:

       Name  Age    Place
0     Suraj   34   Jaipur
1     Aditi   44  Kolkata
2  Priyanka   50     Pune

In [92]:
dfe2=pd.read_excel(r'C:\Users\hp\Downloads\employee.xlsx',sheet_name="Detail2")
print("Sheet 2 details:\n")
dfe2

Sheet 2 details:

     Name  Age    Place
0  Suresh   74   Jaipur
1   Pinku   44  Dhanbad
2  Ramesh   80    Patna

In [95]:
dfe2.index=["Employee1","Employee2","Employee3"]  #changing indices that are saved in original dataframe
dfe2

             Name  Age    Place
Employee1  Suresh   74   Jaipur
Employee2   Pinku   44  Dhanbad
Employee3  Ramesh   80    Patna

In [103]:
dfe2.reset_index(drop=True)

     Name  Age    Place
0  Suresh   74   Jaipur
1   Pinku   44  Dhanbad
2  Ramesh   80    Patna

In [99]:
dfe2

             Name  Age    Place
Employee1  Suresh   74   Jaipur
Employee2   Pinku   44  Dhanbad
Employee3  Ramesh   80    Patna